Update user groups for demo editor
LuckPerms/LuckPermsWeb pull request #464
Opened 2023-11-08 10:37 UTC by Evidentsinger14

Aberdeener - group.mod
ImDarkLaw + group.mod
Leotomas + group.mod
Ev1dent + group.mod

2023-11-08 10:46 UTC, powercasgamer approved these changes

2023-11-11 23:59 UTC, LeotomasMC requested changes

2023-11-11 23:59 UTC, LeotomasMC commented on src/data/editor-demo.json
> +      "displayName": "Leotomas",
i actually have changed my username https://namemc.com/profile/BNTFryingPan.1

2023-11-11 23:59 UTC, LeotomasMC commented on src/data/editor-demo.json
> +      "displayName": "Leotomas",
weird git diff lmao

2023-11-12 00:02 UTC, Evidentsinger14 commented on src/data/editor-demo.json
> +      "displayName": "Leotomas",
Fixed, ty

2023-11-12 05:53 UTC, Turbotailz commented
TYVM

2023-11-12 05:53 UTC, merged